feat: parsing and lexer error reporting (#8)
**Description**

This PR adds:
- fix: build.rs always running because `cargo:rerun-if-changed` was
missing
- Rust like lexer and parsing error reporting
- Simple cli interface
- Updates the readme file
- Creates the input folder with a default file to run
- Displays the final parsing file in terminal output

**Error report example**

```
error: Parser error: unexpected token: "convDate" expected one of: ")"
  --> ./inputs/test.txt:31:5
   |
 31|     convDate(9,9,1999)
   |     ^^^^^^^^ Parser error: unexpected token: "convDate" expected one of: ")"

```